# ========================================
# PERFIL DE DESARROLLO
# ========================================

app.info.environment=dev

# Cambiamos la descripción para saber
# que estamos ejecutando el perfil DEV.
app.info.description=Aplicacion ejecutandose en modo desarrollo


# ========================================
# LOGS
# ========================================

# Mostramos más información en consola
# mientras estamos desarrollando.
logging.level.root=INFO

# Logs de nuestro proyecto
logging.level.com.example.Proyecto1=DEBUG

# Muestra en consola el SQL que genera JPA
spring.jpa.show-sql=true


# ========================================
# ACTUATOR
# ========================================

# En desarrollo mostramos el detalle de health (db, disco...)
management.endpoint.health.show-details=always
