# ========================================
# PERFIL DE PRODUCCION
# ========================================

app.info.environment=prod

# Descripción para identificar
# que estamos usando producción.
app.info.description=Aplicacion ejecutandose en produccion


# ========================================
# LOGS
# ========================================

# En producción normalmente mostramos
# menos información que en desarrollo.
logging.level.root=WARN


# ========================================
# ACTUATOR
# ========================================

# En producción no revelamos detalles internos
management.endpoint.health.show-details=never
